apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  build:
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1
      - name: Setup git credentials
        uses: cloudbees-io/configure-git-global-credentials@v1
      - name: Configure JFrog OCI credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: cbjfrog.saas-preprod.beescloud.com
          username: admin
          password: ${{ secrets.JFROG_TOKEN }}
      - name: run external github workflow
        uses: https://github.com/cloudbees-io/ghactions-run-workflow@v2
        with:
          token: ${{ secrets.GH_SECURITY_PAT_PB}}
          org-name: cloudbees-compliance
          repo-name: demo-go-service
          branch-name: gk_gha
          workflow-name: 'my-gha-workflow'
